name: Build release

on: [push]

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'v')"
    runs-on: macos-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install RPM with Homebrew
        run: brew install rpm
      
      - name: Install Dependencies
        run: npm i

      - name: Build App
        run: npm run build -mwl --publish always
