name: Build release

on: 
  push:
    branches:
      - main

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'v')"
    runs-on: macos-latest

    steps:
      - name: Clone Repo
        run: git clone https://github.com/Rajdeep-TG/electron-app-store

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install RPM with Homebrew
        run: brew install rpm
        
      - name: Install Yarn
        run: npm i -g yarn@latest
      
      - name: Install Dependencies and Build App
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: cd electron-app-store && yarn && yarn build -mwl --publish always
